### ISSUE TITLE
Deprecated Objective-C method

### ISSUE THREAD

**Issue by juancarlosqr** [dev-family/react-native-device-country#2]
Hi, the method for getting the carrier country code in Objective-C is [deprecated](https://developer.apple.com/documentation/coretelephony/cttelephonynetworkinfo). Is there any plan to use `serviceSubscriberCellularProviders` instead?

Thanks

**Comment by mshekspirtt** [comment]
Fixed in version 1.0.2.
https://github.com/dev-family/react-native-device-country/blob/main/CHANGELOG.md
