### ISSUE TITLE
Does this work with expo? [TypeError: Cannot read property 'getCountryCode' of null]

### ISSUE THREAD

**Issue by ghost** [dev-family/react-native-device-country#6]
I get the error: `[TypeError: Cannot read property 'getCountryCode' of null]` when copying the example in the readme. Using expo

**Comment by devthejo** [comment]
running `expo prebuild` and then restart the development server solved this issue for me

**Comment by ngima** [comment]
Alternatively, you can use `dev-client` build.

Basically, it will allow you to install the any libraries with native module without need to have `ios` or `android` folders in your expo project.

https://docs.expo.dev/develop/development-builds/introduction/#what-is-expo-dev-client

**Comment by vaporvee** [comment]
still have the same issue tried all of the above but couldn't run expo prebuild
